#!/usr/bin/env bash
# Interactive Fireworks key-setup helper. Run this in your own terminal
# (not via Claude Code) so the key never enters a transcript.
#
# Usage:
#   cd /Users/luis/smithers/examples/smithers-port-py
#   ./setup-fireworks-key.sh
#
# This appends FIREWORKS_API_KEY to .env.local. If .env.local already
# exists, the existing keys are preserved.
set -euo pipefail

cd "$(dirname "$0")"

if ! git check-ignore .env.local >/dev/null 2>&1; then
  echo "warning: .env.local is not gitignored from this directory."
  echo "Aborting to prevent accidental commit of secrets."
  exit 1
fi

if [[ -f .env.local ]] && grep -q '^FIREWORKS_API_KEY=' .env.local; then
  printf 'FIREWORKS_API_KEY already set in .env.local. Overwrite? [y/N] '
  read -r answer
  case "$answer" in
    y|Y|yes) ;;
    *) echo "Aborted; existing FIREWORKS_API_KEY left in place."; exit 0;;
  esac
  # Strip the existing line; we re-append a fresh one below.
  grep -v '^FIREWORKS_API_KEY=' .env.local > .env.local.tmp
  mv .env.local.tmp .env.local
fi

printf 'Paste your FIREWORKS_API_KEY (input hidden): '
# -s: hide echo, like a password prompt. -r: don't interpret backslashes.
read -rs FIREWORKS_KEY
echo

if [[ -z "${FIREWORKS_KEY:-}" ]]; then
  echo "Empty input; aborted."
  exit 1
fi

# Fireworks keys typically start with "fw_" (per their docs as of 2026).
# Warn but allow override in case the prefix changes.
if [[ "$FIREWORKS_KEY" != fw_* ]]; then
  echo "warning: key doesn't start with 'fw_'. Proceed anyway? [y/N]"
  read -r answer
  case "$answer" in
    y|Y|yes) ;;
    *) echo "Aborted."; exit 1;;
  esac
fi

umask 077
{
  if [[ -f .env.local ]]; then
    cat .env.local
    # Ensure a trailing newline before our append.
    if [[ -n "$(tail -c1 .env.local 2>/dev/null)" ]]; then
      echo
    fi
  else
    echo "# Auto-generated by setup-fireworks-key.sh / setup-key.sh — do NOT commit."
  fi
  echo "FIREWORKS_API_KEY=$FIREWORKS_KEY"
  echo "# Default Fireworks base URL; the OpenAI-compatible API lives here."
  if [[ -f .env.local ]] && grep -q '^FIREWORKS_BASE_URL=' .env.local; then
    : # already set; preserve user override
  else
    echo "FIREWORKS_BASE_URL=https://api.fireworks.ai/inference/v1"
  fi
} > .env.local.new

mv .env.local.new .env.local
chmod 600 .env.local

echo "Wrote .env.local with mode 600 (FIREWORKS_API_KEY appended)."
echo "To verify bun loads it correctly:"
echo "  unset FIREWORKS_API_KEY; bun -e 'console.log(\"loaded:\", process.env.FIREWORKS_API_KEY ? \"yes len=\" + process.env.FIREWORKS_API_KEY.length : \"no\")'"
echo
echo "Note: bun honors shell-env over .env.local, so 'unset FIREWORKS_API_KEY'"
echo "in any shell that already has a stale value before running smithers."
