#!/usr/bin/env bash
# Interactive key-setup helper. Run this in your own terminal (not via
# Claude Code) so the key never enters a transcript.
#
# Usage:
#   cd /Users/luis/smithers/examples/smithers-port-py
#   ./setup-key.sh
set -euo pipefail

cd "$(dirname "$0")"

# Hard ensure .env.local can't accidentally end up in git.
if ! git check-ignore .env.local >/dev/null 2>&1; then
  echo "warning: .env.local is not gitignored from this directory."
  echo "Aborting to prevent accidental commit of secrets."
  exit 1
fi

if [[ -f .env.local ]]; then
  printf '.env.local already exists. Overwrite? [y/N] '
  read -r answer
  case "$answer" in
    y|Y|yes) ;;
    *) echo "Aborted; existing .env.local left in place."; exit 0;;
  esac
fi

printf 'Paste your ANTHROPIC_API_KEY (input hidden): '
# -s: hide echo, like a password prompt. -r: don't interpret backslashes.
read -rs ANTHROPIC_KEY
echo

if [[ -z "${ANTHROPIC_KEY:-}" ]]; then
  echo "Empty input; aborted."
  exit 1
fi
if [[ "$ANTHROPIC_KEY" != sk-ant-* ]]; then
  echo "warning: key doesn't start with 'sk-ant-'. Proceed anyway? [y/N]"
  read -r answer
  case "$answer" in
    y|Y|yes) ;;
    *) echo "Aborted."; exit 1;;
  esac
fi

umask 077
cat > .env.local <<EOF
# Auto-generated by setup-key.sh — do NOT commit.
ANTHROPIC_API_KEY=$ANTHROPIC_KEY
EOF
chmod 600 .env.local

echo "Wrote .env.local with mode 600."
echo "To verify bun loads it correctly:"
echo "  bun -e 'console.log(\"loaded:\", process.env.ANTHROPIC_API_KEY ? \"yes\" : \"no\")'"
