/** @jsxImportSource smithers-orchestrator */
import { createSmithers } from "smithers-orchestrator";
import { z } from "zod";

import { stableNodeId } from "../components/sync-rules.ts";
import {
  classificationSummarySchema,
  prDraftSchema,
  translationSummarySchema,
} from "../components/schemas.ts";

const inputSchema = z.object({
  forkRepo: z.string(),
  forkBranch: z.string(),
  classifications: classificationSummarySchema,
  translations: translationSummarySchema,
  emitPullRequests: z.boolean(),
});

const { Workflow, Task, Sequence, smithers, outputs } = createSmithers(
  {
    input: inputSchema,
    output: prDraftSchema,
  },
  { dbPath: process.env.SMITHERS_PORT_SYNC_DB ?? "smithers.db" },
);

export default smithers((ctx) => (
  <Workflow name="port-sync-pr-emit">
    <Sequence>
      <Task id="pr:emit" output={outputs.output}>
        {() => {
          const drafted = ctx.input.translations.rows.filter(
            (r) => r.status === "drafted",
          );
          if (drafted.length === 0) {
            return {
              schema_version: "smithers-port-sync-pr-draft-v0" as const,
              upstreamPrNumber: 0,
              forkBranch: ctx.input.forkBranch,
              title: "",
              body: "",
              filesChanged: [],
              status: "skipped" as const,
              pullRequestUrl: "",
            };
          }
          // Aggregate all drafted translations into one PR. The TS
          // bun-port pattern is one-PR-per-area; for sync we batch
          // the per-poll deltas into a single PR for review economy.
          const upstreamNums = drafted.map((d) => d.prNumber);
          const titles = drafted
            .map((d) => `#${d.prNumber}`)
            .slice(0, 5)
            .join(", ");
          const branch = `port/sync/batch-${Date.now()}`;
          const title = `[port-sync] Mirror upstream ${titles}` +
            (drafted.length > 5 ? ` and ${drafted.length - 5} more` : "");
          const body = [
            "Auto-generated port-sync PR.",
            "",
            "Upstream PRs mirrored in this batch:",
            ...drafted.map((d) =>
              `- smithersai/smithers#${d.prNumber} → ${d.pythonTarget}`,
            ),
            "",
            "Generated by `examples/smithers-port-py/workflow.tsx`.",
          ].join("\n");
          // In dry mode we just draft. Real mode would call gh pr
          // create here.
          const status = ctx.input.emitPullRequests ? "opened" : "drafted";
          return {
            schema_version: "smithers-port-sync-pr-draft-v0" as const,
            upstreamPrNumber: upstreamNums[0] ?? 0,
            forkBranch: branch,
            title,
            body,
            filesChanged: drafted.map((d) => d.pythonTarget),
            status,
            pullRequestUrl: "",
          };
        }}
      </Task>
    </Sequence>
  </Workflow>
));
