/**
 * @typedef {import('./agentTrace.ts').AgentFamily} AgentFamily
 * @typedef {import('./agentTrace.ts').AgentTraceCapabilityProfile} AgentTraceCapabilityProfile
 */

/** @type {Record<AgentFamily, AgentTraceCapabilityProfile>} */
export const agentTraceCapabilities = {
    pi: {
        sessionMetadata: true,
        assistantTextDeltas: true,
        visibleThinkingDeltas: true,
        finalAssistantMessage: true,
        toolExecutionStart: true,
        toolExecutionUpdate: true,
        toolExecutionEnd: true,
        retryEvents: true,
        compactionEvents: true,
        rawStderrDiagnostics: true,
        persistedSessionArtifact: true,
    },
    codex: {
        sessionMetadata: false,
        assistantTextDeltas: false,
        visibleThinkingDeltas: false,
        finalAssistantMessage: true,
        toolExecutionStart: false,
        toolExecutionUpdate: false,
        toolExecutionEnd: false,
        retryEvents: false,
        compactionEvents: false,
        rawStderrDiagnostics: true,
        persistedSessionArtifact: false,
    },
    "claude-code": {
        sessionMetadata: false,
        assistantTextDeltas: true,
        visibleThinkingDeltas: false,
        finalAssistantMessage: true,
        toolExecutionStart: false,
        toolExecutionUpdate: false,
        toolExecutionEnd: false,
        retryEvents: false,
        compactionEvents: false,
        rawStderrDiagnostics: true,
        persistedSessionArtifact: false,
    },
    gemini: {
        sessionMetadata: false,
        assistantTextDeltas: false,
        visibleThinkingDeltas: false,
        finalAssistantMessage: true,
        toolExecutionStart: false,
        toolExecutionUpdate: false,
        toolExecutionEnd: false,
        retryEvents: false,
        compactionEvents: false,
        rawStderrDiagnostics: true,
        persistedSessionArtifact: false,
    },
    kimi: {
        sessionMetadata: false,
        assistantTextDeltas: false,
        visibleThinkingDeltas: false,
        finalAssistantMessage: true,
        toolExecutionStart: false,
        toolExecutionUpdate: false,
        toolExecutionEnd: false,
        retryEvents: false,
        compactionEvents: false,
        rawStderrDiagnostics: true,
        persistedSessionArtifact: false,
    },
    openai: {
        sessionMetadata: false,
        assistantTextDeltas: false,
        visibleThinkingDeltas: false,
        finalAssistantMessage: true,
        toolExecutionStart: true,
        toolExecutionUpdate: false,
        toolExecutionEnd: true,
        retryEvents: false,
        compactionEvents: false,
        rawStderrDiagnostics: false,
        persistedSessionArtifact: false,
    },
    anthropic: {
        sessionMetadata: false,
        assistantTextDeltas: false,
        visibleThinkingDeltas: false,
        finalAssistantMessage: true,
        toolExecutionStart: true,
        toolExecutionUpdate: false,
        toolExecutionEnd: true,
        retryEvents: false,
        compactionEvents: false,
        rawStderrDiagnostics: false,
        persistedSessionArtifact: false,
    },
    amp: {
        sessionMetadata: false,
        assistantTextDeltas: false,
        visibleThinkingDeltas: false,
        finalAssistantMessage: true,
        toolExecutionStart: true,
        toolExecutionUpdate: false,
        toolExecutionEnd: true,
        retryEvents: false,
        compactionEvents: false,
        rawStderrDiagnostics: true,
        persistedSessionArtifact: false,
    },
    forge: {
        sessionMetadata: false,
        assistantTextDeltas: false,
        visibleThinkingDeltas: false,
        finalAssistantMessage: true,
        toolExecutionStart: true,
        toolExecutionUpdate: false,
        toolExecutionEnd: true,
        retryEvents: false,
        compactionEvents: false,
        rawStderrDiagnostics: true,
        persistedSessionArtifact: false,
    },
    unknown: {
        sessionMetadata: false,
        assistantTextDeltas: false,
        visibleThinkingDeltas: false,
        finalAssistantMessage: true,
        toolExecutionStart: true,
        toolExecutionUpdate: false,
        toolExecutionEnd: true,
        retryEvents: false,
        compactionEvents: false,
        rawStderrDiagnostics: true,
        persistedSessionArtifact: false,
    },
};
